// packages/odk-web-forms/src/components/XForm/debugging/XFormUnknownControl.tsx
import { For } from 'solid-js';
import { Box } from 'suid/material';
import type { XFormViewChildType } from '../../../lib/xform/XFormViewChild.ts';
import type { XFormControlProps } from '../XFormControl.tsx';
import { XFormControl } from '../XFormControl.tsx';
import { XFormAlert } from './XFormAlert.tsx';

interface XFormUnknownControlProps extends XFormControlProps<XFormViewChildType> {}

export const XFormUnknownControl = (props: XFormUnknownControlProps) => {
	return (
		<Box>
			<XFormAlert
				severity="error"
				title={
					<>
						Unrecognized form control: <code>{props.viewControl.type}</code>
					</>
				}
				detailsSummary="Control"
			>
				<pre>{JSON.stringify(props, null, 2)}</pre>
			</XFormAlert>
			<For each={props.viewControl.children}>
				{(childViewControl) => {
					return <XFormControl entry={props.entry} viewControl={childViewControl} />;
				}}
			</For>
		</Box>
	);
};

// packages/ui-solid/src/components/XForm/debugging/XFormUnknownControl.tsx
import type { ValueNodeState } from '@odk-web-forms/xforms-engine';
import { Box } from '@suid/material';
import { XFormAlert } from './XFormAlert.tsx';

interface XFormUnknownControlProps {
	readonly state: ValueNodeState;
}

export const XFormUnknownControl = (props: XFormUnknownControlProps) => {
	const element = () => props.state.definition.bodyElement;

	return (
		<Box>
			<XFormAlert
				severity="error"
				title={
					<>
						Unrecognized form control: <code>{element()?.type}</code>
					</>
				}
				detailsSummary="Control"
			>
				<pre>{JSON.stringify(props, null, 2)}</pre>
			</XFormAlert>
		</Box>
	);
};
